# Generated by Django 5.1.7 on 2025-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('price_band', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.CharField(max_length=100)),
                ('listing_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('ipo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rhp_pdf', models.FileField(upload_to='pdfs/')),
                ('drhp_pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
